# This file configures the production deployment workflow

name: Deploy to Firebase Hosting on prod branch push
'on':
  push:
    branches:
      - prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CME_FACEBOOK_2 }}'
          channelId: live
          projectId: cme-facebook-2 